// Latin-1 named entities; combining-mark Vietnamese letters (ạ, ầ, ộ, …) have no
// named form and only ever appear as numeric refs, handled by the `#…` branch below.
const NAMED_ENTITIES: Record<string, string> = {
  amp: "&",
  lt: "<",
  gt: ">",
  quot: '"',
  apos: "'",
  nbsp: " ",
  Aacute: "Á",
  aacute: "á",
  Agrave: "À",
  agrave: "à",
  Acirc: "Â",
  acirc: "â",
  Atilde: "Ã",
  atilde: "ã",
  Auml: "Ä",
  auml: "ä",
  Aring: "Å",
  aring: "å",
  AElig: "Æ",
  aelig: "æ",
  Ccedil: "Ç",
  ccedil: "ç",
  Eacute: "É",
  eacute: "é",
  Egrave: "È",
  egrave: "è",
  Ecirc: "Ê",
  ecirc: "ê",
  Euml: "Ë",
  euml: "ë",
  Iacute: "Í",
  iacute: "í",
  Igrave: "Ì",
  igrave: "ì",
  Icirc: "Î",
  icirc: "î",
  Iuml: "Ï",
  iuml: "ï",
  Ntilde: "Ñ",
  ntilde: "ñ",
  Oacute: "Ó",
  oacute: "ó",
  Ograve: "Ò",
  ograve: "ò",
  Ocirc: "Ô",
  ocirc: "ô",
  Otilde: "Õ",
  otilde: "õ",
  Ouml: "Ö",
  ouml: "ö",
  Oslash: "Ø",
  oslash: "ø",
  Uacute: "Ú",
  uacute: "ú",
  Ugrave: "Ù",
  ugrave: "ù",
  Ucirc: "Û",
  ucirc: "û",
  Uuml: "Ü",
  uuml: "ü",
  Yacute: "Ý",
  yacute: "ý",
  yuml: "ÿ",
  THORN: "Þ",
  thorn: "þ",
  ETH: "Ð",
  eth: "ð",
  szlig: "ß",
  times: "×",
  divide: "÷",
  deg: "°",
  plusmn: "±",
  sup2: "²",
  sup3: "³",
  micro: "µ",
  para: "¶",
  middot: "·",
  cedil: "¸",
  ordf: "ª",
  ordm: "º",
  laquo: "«",
  raquo: "»",
  iquest: "¿",
  iexcl: "¡",
  curren: "¤",
  cent: "¢",
  pound: "£",
  yen: "¥",
  sect: "§",
  copy: "©",
  reg: "®",
  trade: "™",
  hellip: "…",
  mdash: "—",
  ndash: "–",
  lsquo: "‘",
  rsquo: "’",
  ldquo: "“",
  rdquo: "”",
  bull: "•",
  dagger: "†",
  Dagger: "‡",
  permil: "‰",
  euro: "€",
};

/** Decodes named + numeric (`&#123;` / `&#x7B;`) HTML entities in plain text. */
export function decodeHtmlEntities(text: string): string {
  return text.replace(
    /&(#x[0-9a-fA-F]+|#[0-9]+|[a-zA-Z][a-zA-Z0-9]*);/g,
    (match, ref: string) => {
      if (ref[0] === "#") {
        const codePoint =
          ref[1] === "x" || ref[1] === "X"
            ? parseInt(ref.slice(2), 16)
            : parseInt(ref.slice(1), 10);
        return Number.isFinite(codePoint) ? String.fromCodePoint(codePoint) : match;
      }
      return NAMED_ENTITIES[ref] ?? match;
    },
  );
}
